/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Fires when the plugin is initialized
 */
export declare function onInitialize(serenity: Serenity, plugin: Plugin): void
/**
 * Fire when the plugin is started
 */
export declare function onStartup(serenity: Serenity, plugin: Plugin): void
/**
 * Fire when the plugin is stopped
 */
export declare function onShutdown(serenity: Serenity, plugin: Plugin): void
export declare function beforePlayerChat(event: PlayerChatSignal): boolean
export type Vector3f = Vector3F
export declare class Vector3F {
  x: number
  y: number
  z: number
}
export declare class BlockPosition {
  x: number
  y: number
  z: number
}
